2025-05-08 15:15:32,703 - exploit_routes - ERROR - [exploit_routes.py:80] - Erreur lors de la récupération des rapports: exploit_reports.html
Traceback (most recent call last):
  File "/home/oebn/toolbox/routes/exploit_routes.py", line 78, in list_reports
    return render_template("exploit_reports.html", reports=reports)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: exploit_reports.html
2025-05-08 15:15:42,200 - exploit_routes - ERROR - [exploit_routes.py:80] - Erreur lors de la récupération des rapports: exploit_reports.html
Traceback (most recent call last):
  File "/home/oebn/toolbox/routes/exploit_routes.py", line 78, in list_reports
    return render_template("exploit_reports.html", reports=reports)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: exploit_reports.html
2025-05-08 17:38:43,740 - exploit_routes - INFO - [exploit_routes.py:153] - Vérification de l'exploitabilité de: ssl-ccs-injection
2025-05-08 17:38:43,743 - exploit_routes - INFO - [exploit_routes.py:160] - Module trouvé pour ssl-ccs-injection: auxiliary/scanner/ssl/openssl_ccs
2025-05-08 17:38:58,371 - exploit_routes - INFO - [exploit_routes.py:23] - Requête reçue pour lancer un exploit
2025-05-08 17:42:57,247 - exploit_routes - INFO - [exploit_routes.py:88] - Accès à la liste des rapports d'exploitation
2025-05-08 17:42:57,257 - exploit_routes - ERROR - [exploit_routes.py:98] - Erreur lors de la récupération des rapports: exploit_reports.html
Traceback (most recent call last):
  File "/home/oebn/toolbox/routes/exploit_routes.py", line 96, in list_reports
    return render_template("exploit_reports.html", reports=reports)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: exploit_reports.html
2025-05-08 17:43:42,444 - exploit_routes - INFO - [exploit_routes.py:153] - Vérification de l'exploitabilité de: http-slowloris-check
2025-05-08 17:43:42,455 - exploit_routes - INFO - [exploit_routes.py:160] - Module trouvé pour http-slowloris-check: auxiliary/dos/http/slowloris
2025-05-08 17:43:48,175 - exploit_routes - INFO - [exploit_routes.py:153] - Vérification de l'exploitabilité de: ssl-poodle
2025-05-08 17:43:48,175 - exploit_routes - INFO - [exploit_routes.py:160] - Module trouvé pour ssl-poodle: auxiliary/scanner/ssl/openssl_fallback_check
2025-05-08 17:43:51,493 - exploit_routes - INFO - [exploit_routes.py:153] - Vérification de l'exploitabilité de: ssl-dh-params
2025-05-08 17:43:51,494 - exploit_routes - INFO - [exploit_routes.py:160] - Module trouvé pour ssl-dh-params: auxiliary/scanner/ssl/ssl_version
2025-05-08 17:43:54,129 - exploit_routes - INFO - [exploit_routes.py:153] - Vérification de l'exploitabilité de: ssl-ccs-injection
2025-05-08 17:43:54,129 - exploit_routes - INFO - [exploit_routes.py:160] - Module trouvé pour ssl-ccs-injection: auxiliary/scanner/ssl/openssl_ccs
2025-05-08 17:43:56,655 - exploit_routes - INFO - [exploit_routes.py:153] - Vérification de l'exploitabilité de: http-vuln-cve2014-3704
2025-05-08 17:43:56,655 - exploit_routes - INFO - [exploit_routes.py:160] - Module trouvé pour http-vuln-cve2014-3704: exploit/unix/webapp/drupal_drupalgeddon
2025-05-08 17:44:47,407 - exploit_routes - INFO - [exploit_routes.py:153] - Vérification de l'exploitabilité de: ssl-dh-params
2025-05-08 17:44:47,408 - exploit_routes - INFO - [exploit_routes.py:160] - Module trouvé pour ssl-dh-params: auxiliary/scanner/ssl/ssl_version
2025-05-08 17:45:09,878 - exploit_routes - INFO - [exploit_routes.py:23] - Requête reçue pour lancer un exploit
